In [4]:
import os

import torch

In [1]:
import pandas as pd
df = pd.read_csv('./input/train.csv')

In [2]:
df.loc[df.cat3 =='항구/포구'].sample(5)[['overview','cat3']]

overview   cat3
11266  1971년 국가 어항으로 지정된 방어진항은 넓은 부지의 수협위판장과 경매장이 있는 ...  항구/포구
1248   격포항은 해양수산부에서 선정한 우리나라 '아름다운 어촌 100개소' 중 한곳으로, ...  항구/포구
6719   안면대교를 건너 만나는 첫 삼거리에서 오른쪽으로 조금 들어가면 나온다. 포구에는 횟...  항구/포구
1671   왜목마을은 충남 당진시 서해의 최북단에 있는 마을이다. 지형적으로 바다를 동서로 양...  항구/포구
7480   보성군 회천면 율포리에 있는 율포항은 1972년 지방 어항으로 지정되었고, 태풍 내...  항구/포구

In [3]:
sentences = df.overview.values
labels = df['cat3'].astype('category').cat.codes

In [4]:
from transformers import BertTokenizer,RobertaTokenizer

In [163]:
# Load the BERT tokenizer

# RobertTokenizer.from_pretrained('klue/robert-large')

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased', do_lower_case=True)
# Print the original sentence.
print(' Original: ', sentences[0])

# Print the sentence split into tokens.
print('Tokenized: ', tokenizer.tokenize(sentences[0]))

# Print the sentence mapped to token ids
print('Token IDs: ', tokenizer.convert_tokens_to_ids(tokenizer.tokenize(sentences[0])))

In [9]:
from transformers import BertTokenizer,AutoTokenizer
tokenizer = BertTokenizer.from_pretrained('monologg/kobert')
tokenizer

PreTrainedTokenizer(name_or_path='monologg/kobert', vocab_size=8002, model_max_len=512, is_fast=False, padding_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'})

In [10]:
print(' Original: ', sentences[0])

# Print the sentence split into tokens.
print('Tokenized: ', tokenizer.tokenize(sentences[0]))

# Print the sentence mapped to token ids
print('Token IDs: ', tokenizer.convert_tokens_to_ids(tokenizer.tokenize(sentences[0])))

 Original:  소안항은 조용한 섬으로 인근해안이 청정해역으로 일찍이 김 양식을 해서 높은 소득을 올리고 있으며 바다낚시터로도 유명하다. 항 주변에 설치된 양식장들은 섬사람들의 부지런한 생활상을 고스 란히 담고 있으며 일몰 때 섬의 정경은 바다의 아름다움을 그대로 품고 있는 듯하다. 또한, 섬에는 각시여 전설, 도둑바위 등의 설화가 전해 내려오고 있으며, 매년 정월 풍어제 풍속이 이어지고 있다.<br>
Tokenized:  ['[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '김', '[UNK]', '해서', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '.', '항', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '때', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '있는', '[UNK]', '.', '[UNK]', ',', '[UNK]', '[UNK]', '[UNK]', ',', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', ',', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '있다', '.', '<', '[UNK]', '>']
Token IDs:  [0, 0, 0, 0, 0, 0, 5586, 0, 7850, 0, 0, 0, 0, 0, 0, 54, 7846, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5965, 0, 0, 0, 0, 0, 0, 7142, 0, 54, 0, 46, 0, 0, 0, 46, 0, 0, 0, 0, 0, 0, 46, 0, 0, 0, 0, 0, 7143, 54, 253, 0, 257]


In [13]:
from kobert.utils.utils import download, get_tokenizer

ModuleNotFoundError: No module named 'kobert'

In [12]:
# tokenizer에 따라 UNK가 너무많다 확실히


tokenizer_path = get_tokenizer()
tokenizer = nlp.data.BERTSPTokenizer(tokenizer_path,vocab,lower=False)
#tokenizer = KoBertTokenizer.from_pretrained(pt,  cache_dir='bert_ckpt', do_lower_case=False)

NameError: name 'args' is not defined

In [165]:
print(' Original: ', sentences[0])

# Print the sentence split into tokens.
print('Tokenized: ', tokenizer.tokenize(sentences[0]))

# Print the sentence mapped to token ids
print('Token IDs: ', tokenizer.convert_tokens_to_ids(tokenizer.tokenize(sentences[0])))

 Original:  소안항은 조용한 섬으로 인근해안이 청정해역으로 일찍이 김 양식을 해서 높은 소득을 올리고 있으며 바다낚시터로도 유명하다. 항 주변에 설치된 양식장들은 섬사람들의 부지런한 생활상을 고스 란히 담고 있으며 일몰 때 섬의 정경은 바다의 아름다움을 그대로 품고 있는 듯하다. 또한, 섬에는 각시여 전설, 도둑바위 등의 설화가 전해 내려오고 있으며, 매년 정월 풍어제 풍속이 이어지고 있다.<br>
Tokenized:  ['ᄉ', '##ᅩ', '##ᄋ', '##ᅡ', '##ᆫ', '##ᄒ', '##ᅡ', '##ᆼ', '##ᄋ', '##ᅳ', '##ᆫ', 'ᄌ', '##ᅩ', '##ᄋ', '##ᅭ', '##ᆼ', '##ᄒ', '##ᅡ', '##ᆫ', 'ᄉ', '##ᅥ', '##ᆷ', '##ᄋ', '##ᅳ', '##ᄅ', '##ᅩ', 'ᄋ', '##ᅵ', '##ᆫ', '##ᄀ', '##ᅳ', '##ᆫ', '##ᄒ', '##ᅢ', '##ᄋ', '##ᅡ', '##ᆫ', '##ᄋ', '##ᅵ', 'ᄎ', '##ᅥ', '##ᆼ', '##ᄌ', '##ᅥ', '##ᆼ', '##ᄒ', '##ᅢ', '##ᄋ', '##ᅧ', '##ᆨ', '##ᄋ', '##ᅳ', '##ᄅ', '##ᅩ', '[UNK]', 'ᄀ', '##ᅵ', '##ᆷ', '[UNK]', 'ᄒ', '##ᅢ', '##ᄉ', '##ᅥ', '[UNK]', 'ᄉ', '##ᅩ', '##ᄃ', '##ᅳ', '##ᆨ', '##ᄋ', '##ᅳ', '##ᆯ', 'ᄋ', '##ᅩ', '##ᆯ', '##ᄅ', '##ᅵ', '##ᄀ', '##ᅩ', '[UNK]', '[UNK]', 'ᄋ', '##ᅲ', '##ᄆ', '##ᅧ', '##ᆼ', '##ᄒ', '##ᅡ', '##ᄃ', '##ᅡ', '.', 'ᄒ', '##ᅡ', '##ᆼ', 'ᄌ', '##ᅮ', '##ᄇ', '##ᅧ', '##ᆫ', '##ᄋ', '##ᅦ', '[UNK]', '[UNK]', 'ᄉ', '##ᅥ', '##ᆷ', '##ᄉ', '##ᅡ', '##ᄅ', '##ᅡ', '

In [157]:
tokenizer

PreTrainedTokenizer(name_or_path='bert-base-uncased', vocab_size=30522, model_max_len=512, is_fast=False, padding_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'})

In [10]:
# Tokenize all of the sentences and map the tokens to thier word IDs
input_ids =[]

# For every sentence..

for sent in sentences:
    encoded_sent = tokenizer.encode(

        sent
    )

    # Add the encoded sentence to the list
    input_ids.append(encoded_sent)

# Print sentence 0 , now as a list of IDs

print('Original :' , sentences[0])
print('Token IDs: ', input_ids[0])

print('Max sentence lenght:' , max([len(sen) for sen in input_ids]))

Token indices sequence length is longer than the specified maximum sequence length for this model (526 > 512). Running this sequence through the model will result in indexing errors


Original : 소안항은 조용한 섬으로 인근해안이 청정해역으로 일찍이 김 양식을 해서 높은 소득을 올리고 있으며 바다낚시터로도 유명하다. 항 주변에 설치된 양식장들은 섬사람들의 부지런한 생활상을 고스 란히 담고 있으며 일몰 때 섬의 정경은 바다의 아름다움을 그대로 품고 있는 듯하다. 또한, 섬에는 각시여 전설, 도둑바위 등의 설화가 전해 내려오고 있으며, 매년 정월 풍어제 풍속이 이어지고 있다.<br>
Token IDs:  [101, 1461, 30011, 29999, 30006, 30021, 30005, 30006, 30025, 29999, 30017, 30021, 1464, 30011, 29999, 30013, 30025, 30005, 30006, 30021, 1461, 30008, 30023, 29999, 30017, 29994, 30011, 1463, 30019, 30021, 29991, 30017, 30021, 30005, 30007, 29999, 30006, 30021, 29999, 30019, 1465, 30008, 30025, 30000, 30008, 30025, 30005, 30007, 29999, 30010, 30020, 29999, 30017, 29994, 30011, 100, 1455, 30019, 30023, 100, 1469, 30007, 29997, 30008, 100, 1461, 30011, 29993, 30017, 30020, 29999, 30017, 30022, 1463, 30011, 30022, 29994, 30019, 29991, 30011, 100, 100, 1463, 30016, 29995, 30010, 30025, 30005, 30006, 29993, 30006, 1012, 1469, 30006, 30025, 1464, 30014, 29996, 30010, 30021, 29999, 30009, 100, 100, 1461, 30008, 30023, 29997, 30006, 29994, 30006, 30023, 2999

In [11]:
# We will use some utility function from tensorflow (Tensorflow was my first crush)

from keras.preprocessing.sequence import pad_sequences

MAX_LEN = 64
# Padding the input to the max length that is 64
input_ids = pad_sequences(input_ids, maxlen=MAX_LEN, dtype="long", value=0 , truncating='post', padding='post')



c:\users\data\appdata\local\programs\python\python38\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [21]:
# Creating the attention masks
attention_masks = []


# For each sentences..

for sent in input_ids:
    # Create the attention mask
    # - If a  token ID is 0 , then it's padding , set the mask to 0.
    # - If a  token ID is > 0 , then it's a real token, set the mask to 1.
    att_mask = [ int(token_id > 0) for token_id in sent ]

    # Store the attention_mask for this sentence
    attention_masks.append(att_mask)

# We will call the train_test_split() function from sklearn
from sklearn.model_selection import train_test_split

train_inputs, validation_inputs, train_labels,  validation_labels = train_test_split(input_ids, labels, random_state=2018 ,test_size=0.1)

# Performing same steps on the attention masks
train_masks, validation_masks, _, _ = train_test_split(attention_masks, labels , random_state=2018 ,test_size=0.1)

array([[  101,  1461, 30011, ..., 30007, 29997, 30008],
       [  101,  1455, 30010, ..., 30022,   100,  2355],
       [  101,   100,  1469, ..., 29999, 30017, 29994],
       ...,
       [  101,  1465, 30014, ..., 30006, 30021, 29999],
       [  101,   100,  1455, ..., 29999, 30006, 30020],
       [  101,  1468, 30011, ..., 30017, 30022,  1455]])

In [22]:
train_inputs

array([[  101,  1455, 30006, ..., 30014, 30022,   100],
       [  101,  2871, 29992, ..., 29999, 30014, 30022],
       [  101,  1457, 30007, ..., 29994, 30011,  1455],
       ...,
       [  101,   100,  1463, ...,   100,   100,  1461],
       [  101,  1459, 30011, ..., 30000, 30008, 30021],
       [  101,  1463, 30019, ..., 29993, 30009,  1465]])

In [23]:
#Converting the input dat ato the tensor , which can be feeded to the model
train_inputs = torch.tensor(train_inputs)
validation_inputs = torch.tensor(validation_inputs)

In [30]:
train_labels = train_labels.reset_index(drop=True)

In [40]:
validation_labels = validation_labels.values.tolist()

In [41]:
train_labels = torch.tensor(train_labels)
validation_labels = torch.tensor(validation_labels)

C:\Users\DATA\AppData\Local\Temp\ipykernel_9352\3654936025.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  train_labels = torch.tensor(train_labels)


In [42]:
train_masks = torch.tensor(train_masks)
validation_masks = torch.tensor(validation_masks)


In [43]:
from torch.utils.data import TensorDataset, DataLoader , RandomSampler , SequentialSampler

In [ ]:
# Creating the DataLoader which will help us to load data into the GPU/CPU


batch_size = 32


# Create the DataLoader for our training set
train_data = TensorDataset(train_inputs , train_masks , train_labels)
train_sampler = RandomSampler(train_data)

In [ ]:
train_dataloader =  DataLoader(train_data , sampler=train_sampler , batch_size=batch_size)

In [45]:
# Create the DataLoader for our validation set
validation_data = TensorDataset(validation_inputs , validation_masks , validation_labels)

In [46]:
validation_sampler = SequentialSampler(validation_data)

validation_dataloader = DataLoader(validation_data, sampler=validation_sampler, batch_size=batch_size)


PreTrainedTokenizer(name_or_path='monologg/kobert', vocab_size=8002, model_max_len=512, is_fast=False, padding_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'})

In [ ]:
model =  BertForSequenceClassification.from_pretrained("monologg/kobert",
                                                        num_labels = 128,
                                                       output_attentions=False,
                                                       output_hidden_states  = False,)

In [47]:
 from transformers import BertForSequenceClassification, AdamW, BertConfig

In [48]:
model =  BertForSequenceClassification.from_pretrained("monologg/kobert",
                                                        num_labels = 128,
                                                       output_attentions=False,
                                                       output_hidden_states  = False,)

Downloading:   0%|          | 0.00/369M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at monologg/kobert and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [49]:
optimizer = AdamW(model.parameters(), lr=2e-5 , eps=1e-8)

In [50]:
from transformers import get_linear_schedule_with_warmup

epochs = 4

total_steps = len(train_dataloader) * epochs

In [118]:
# 0에서 옵티마이저에 설정된 초기 lr까지 선형적으로 증가하는 워밍업 기간 후에 옵티마이저에 설정된 초기 lr에서 0으로 선형적으로 감소하는 학습률로 스케줄을 생성합니다.
# warmup steps까지는 초기 lr로 워밍업하다가 그 이후 부터 감소하는듯
# warmup 단계까지는 설정한 learning_rate 까지 num_warmuip_steps 에 비례하여 선형적 으로 상승하는 학습률을 만든다 그 후 감쇠
scheduler = get_linear_schedule_with_warmup(optimizer, num_warmup_steps= 5 , num_training_steps=total_steps)

In [127]:
scheduler.get_lr()
scheduler.step()
val = scheduler.get_lr()[0]

c:\users\data\appdata\local\programs\python\python38\lib\site-packages\torch\optim\lr_scheduler.py:247: UserWarning: To get the last learning rate computed by the scheduler, please use `get_last_lr()`.
  warnings.warn("To get the last learning rate computed by the scheduler, "


In [128]:
val

2e-05

In [115]:
int(val)

0

In [85]:
import numpy as np

import time
import datetime


def format_time(elapsed):
    """

    Takes a time in seconds and returns a string hh:mm:ss

    :param elapsed:
    :return:
    """

    # Round to the nearest second
    elasped_rounded = int(round((elapsed)))

    # Format as hh:mm:ss
    return str(datetime.timedelta(seconds=elasped_rounded))

# Let's start the training process
import random

# This training code is based on the 'run_clue.py' script here


seed_val = 42

random.seed(seed_val)
np.random.seed(seed_val)
torch.manual_seed(seed_val)


loss_values = []



c:\users\data\appdata\local\programs\python\python38\lib\site-packages\torch\optim\lr_scheduler.py:247: UserWarning: To get the last learning rate computed by the scheduler, please use `get_last_lr()`.
  warnings.warn("To get the last learning rate computed by the scheduler, "


[1.998952879581152e-05]

c:\users\data\appdata\local\programs\python\python38\lib\site-packages\torch\optim\lr_scheduler.py:247: UserWarning: To get the last learning rate computed by the scheduler, please use `get_last_lr()`.
  warnings.warn("To get the last learning rate computed by the scheduler, "


[2e-05]

c:\users\data\appdata\local\programs\python\python38\lib\site-packages\torch\optim\lr_scheduler.py:247: UserWarning: To get the last learning rate computed by the scheduler, please use `get_last_lr()`.
  warnings.warn("To get the last learning rate computed by the scheduler, "


[1.9937238493723853e-05]

c:\users\data\appdata\local\programs\python\python38\lib\site-packages\torch\optim\lr_scheduler.py:247: UserWarning: To get the last learning rate computed by the scheduler, please use `get_last_lr()`.
  warnings.warn("To get the last learning rate computed by the scheduler, "


[1.9926778242677826e-05]

In [52]:
scheduler
import numpy as np
def flat_accuracy(preds, labels):
    pred_flat = np.argmax(preds, axis=1).flatten()
    labels_flat = labels.flatten()
    return np.sum(pred_flat == labels_flat) / len(labels_flat)

In [129]:
import time
import datetime
def format_time(elapsed):
    """
    Takes a time in seconds and returns a stirng hh:mm: ss

    :param elapsed:
    :return:

    """
    elapsed_rounded = int(round((elapsed)))

    # Format  as hh:mm:ss
    return str(datetime.timedelta(seconds=elapsed_rounded))

In [133]:
for data in train_dataloader:
    break

In [ ]:
# embedding vocab_size 가 8002 인데 넘어가면 out of index인듯 하다
#(word_embeddings): Embedding(8002, 768, padding_idx=1)

tensor([[  101,  1463, 30013,  ..., 29999, 30018,  1463],
        [  101,  3429, 29992,  ..., 30000, 30008, 30020],
        [  101,  1464, 30008,  ..., 30006, 30021,  1457],
        ...,
        [  101,  1465, 30008,  ..., 30011,  1463, 30016],
        [  101,  1460, 30019,  ...,  1461, 30006, 30025],
        [  101,  1464, 30008,  ...,  1455, 30007, 29999]], dtype=torch.int32)

In [153]:
outputs = model(data[0],
                token_type_ids=None,
                attention_mask=data[1])

IndexError: index out of range in self

In [149]:
data[1][0]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [146]:
data[0][0]

tensor([  101,  1463, 30013, 30025, 29999, 30019, 30021, 29997, 30019,  1461,
        30014, 30000, 30019, 29991, 30014,  1457, 30011, 30025, 30001, 30008,
        30021, 29993, 30011, 30025, 29999, 30009,   100,  1469, 30006, 30021,
        29999, 30011, 30020,  1455, 30008, 30021, 29995, 30014, 30022, 29999,
        30018,  1469, 30006, 30021, 29997, 30019, 30020, 29993, 30006, 30025,
        29999, 30019, 29993, 30006,  1012,  1469, 30006, 30021, 29999, 30011,
        30020, 29999, 30018,  1463], dtype=torch.int32)

In [132]:

import random


seed_val = 42

random.seed(seed_val)
np.random.seed(seed_val)
torch.manual_seed(seed_val)
loss_values = []

for epoch_i in range(0, epochs):

    #=======================
    #   TRAINING
    #=======================

    print("")
    print("=========== EPOCH {:} / {:} ==========".format(epoch_i+1,epochs))
    print("Training.....")


    # Measure how long the traingin epochs takes
    t0 = time.time()

    # Reset the total loss for this epoch
    total_loss = 0

    model.train()

    for step, batch in enumerate(train_dataloader):
        if step% 40 == 0 and not step ==0:
            # Calculate elapsed time in minutes
            elapsed = format_time(time.time() - t0)

            # Report progress
            print(' Batch {:>5,} of {:>5,}. Elapsed : {:} .'.format(step , len(train_dataloader), elapsed))


            b_input_ids = batch[0]
            b_input_masks = batch[1]
            b_labels = batch[2]

            model.zero_grad()

            outputs = model(b_input_ids ,
                            token_type_ids=None,
                            attention_masks=b_input_masks,
                            labels=b_labels)

            loss = outputs[0]

            total_loss += loss.item()
            loss.backward()

            torch.nn.utils.clip_grad_norm(model.parameters() , 1.0)


            optimizer.step()

            scheduler.step()

        avg_train_loss =  total_loss / len(train_dataloader)


        loss_values.append(avg_train_loss)

        print("")
        print(" Average traingin loss : {0:.2f}".format(avg_train_loss))
        print(" Training epoch took : {:}".format(format_time(time.time() - t0)))


        print(" ")
        print( " Running Validation")

        t0 = time.time()

        model.eval()

        eval_loss , eval_accuracy = 0, 0
        nb_eval_steps , nb_eval_examples = 0, 0

        # Evaluate data for one epoch
        for batch in validation_dataloader:
            # Add batch to GPU
            batch = tuple(t for t in batch)

            b_input_ids , b_input_masks, b_labels = batch

            with torch.no_grad():


                outputs = model(b_input_ids,
                                token_type_ids=None,
                                attention_mask=b_input_masks)


            logits = outputs[0]

            logits = logits.detach().cpu().numpy()
            label_ids = b_labels.numpy()


            tmp_eval_accuracy = flat_accuracy(logits, label_ids)


            eval_accuracy  += tmp_eval_accuracy

            nb_eval_steps += 1

        #Report the final accuracy for this validation run.

        print(" Accuracy : {0:.2f}".format(eval_accuracy/nb_eval_steps))
        print(" Validation took: {:}".format(format_time(time.time()- t0)))

    print("")
    print("Training complete!")



=========== EPOCH 1 / 4 ==========
Training.....

 Average traingin loss : 0.00
 Training epoch took : 0:00:00
 
 Running Validation


IndexError: index out of range in self

In [ ]:
# if 'obert' in pt:
#     tokenizer = KoBertTokenizer.from_pretrained(pt,  cache_dir='bert_ckpt', do_lower_case=False)
#     print('load kobert')
# else:
#     tokenizer = AutoTokenizer.from_pretrained(args.pt)
