In [16]:
# 다른 거 첨가한다고 결국 재현 안한 (분명 해봤자일거라 생각) 코드

from transformers import AutoTokenizer,AutoModel
from torch.utils.data import Dataset,DataLoader
import pandas as pd
import os

all_df = pd.read_csv('./input/train.csv')

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
all_df['cat1'] = le.fit_transform(all_df['cat1'].values)

In [ ]:
le.classes_

In [17]:
import torch.nn as nn

In [290]:
import torch

In [525]:
# Dataset 을 상속받고 DataLoader 에 넘겨진다.
class CateDataset(Dataset):
    def __init__(self , text , cat1 , tokenizer):
        """
        :param text: 관광지 설명
        :param cat1: 대 카테고리 cat1
        """
        if not isinstance( text,str):
            print('Text must be str')
        self.text = text
        self.cat1 = cat1
        self.tokenizer = tokenizer
        self.tokenizer.enable_padding("right",length=512)

    def __len__(self):
        return len(self.text)

    def __getitem__(self, item):
        text = self.text[item]
        cat1 = self.cat1[item]
        texts  = ""
        if '.' in text:# 문장 형식으로 되있다면
            for sentence in text.split('.'):
                texts+= sentence[:51]
                if len(texts) >= 512:
                    break
        else:
            texts = text

        encoding = self.tokenizer.encode(texts)
        # print(torch.tensor(encoding.ids), torch.tensor(encoding.attention_mask), torch.LongTensor(cat1))
        return torch.tensor(encoding.ids,dtype=torch.long), torch.tensor(encoding.attention_mask,dtype=torch.long), torch.LongTensor([cat1])


In [398]:
from transformers import BertForSequenceClassification, BertConfig

In [318]:
class CateClassifier(nn.Module):
    def __init__(self, n_classes_1 ):
        super(CateClassifier, self).__init__()
        self.text_model = BertForSequenceClassification(BertConfig(vocab_size=42000 ,id2label={
    "0": "0",
    "1": "1",
    "2": "10",
    "3": "100",
    "4": "101",
    "5": "102",
    "6": "103",
    "7": "104",
    "8": "105",
    "9": "106",
    "10": "107",
    "11": "108",
    "12": "109",
    "13": "11",
    "14": "110",
    "15": "111",
    "16": "112",
    "17": "113",
    "18": "114",
    "19": "115",
    "20": "116",
    "21": "117",
    "22": "118",
    "23": "119",
    "24": "12",
    "25": "120",
    "26": "121",
    "27": "122",
    "28": "123",
    "29": "124",
    "30": "125",
    "31": "126",
    "32": "127",
    "33": "13",
    "34": "14",
    "35": "15",
    "36": "16",
    "37": "17",
    "38": "18",
    "39": "19",
    "40": "2",
    "41": "20",
    "42": "21",
    "43": "22",
    "44": "23",
    "45": "24",
    "46": "25",
    "47": "26",
    "48": "27",
    "49": "28",
    "50": "29",
    "51": "3",
    "52": "30",
    "53": "31",
    "54": "32",
    "55": "33",
    "56": "34",
    "57": "35",
    "58": "36",
    "59": "37",
    "60": "38",
    "61": "39",
    "62": "4",
    "63": "40",
    "64": "41",
    "65": "42",
    "66": "43",
    "67": "44",
    "68": "45",
    "69": "46",
    "70": "47",
    "71": "48",
    "72": "49",
    "73": "5",
    "74": "50",
    "75": "51",
    "76": "52",
    "77": "53",
    "78": "54",
    "79": "55",
    "80": "56",
    "81": "57",
    "82": "58",
    "83": "59",
    "84": "6",
    "85": "60",
    "86": "61",
    "87": "62",
    "88": "63",
    "89": "64",
    "90": "65",
    "91": "66",
    "92": "67",
    "93": "68",
    "94": "69",
    "95": "7",
    "96": "70",
    "97": "71",
    "98": "72",
    "99": "73",
    "100": "74",
    "101": "75",
    "102": "76",
    "103": "77",
    "104": "78",
    "105": "79",
    "106": "8",
    "107": "80",
    "108": "81",
    "109": "82",
    "110": "83",
    "111": "84",
    "112": "85",
    "113": "86",
    "114": "87",
    "115": "88",
    "116": "89",
    "117": "9",
    "118": "90",
    "119": "91",
    "120": "92",
    "121": "93",
    "122": "94",
    "123": "95",
    "124": "96",
    "125": "97",
    "126": "98",
    "127": "99"
  }  , label2id= {
    "0": 0,
    "1": 1,
    "10": 2,
    "100": 3,
    "101": 4,
    "102": 5,
    "103": 6,
    "104": 7,
    "105": 8,
    "106": 9,
    "107": 10,
    "108": 11,
    "109": 12,
    "11": 13,
    "110": 14,
    "111": 15,
    "112": 16,
    "113": 17,
    "114": 18,
    "115": 19,
    "116": 20,
    "117": 21,
    "118": 22,
    "119": 23,
    "12": 24,
    "120": 25,
    "121": 26,
    "122": 27,
    "123": 28,
    "124": 29,
    "125": 30,
    "126": 31,
    "127": 32,
    "13": 33,
    "14": 34,
    "15": 35,
    "16": 36,
    "17": 37,
    "18": 38,
    "19": 39,
    "2": 40,
    "20": 41,
    "21": 42,
    "22": 43,
    "23": 44,
    "24": 45,
    "25": 46,
    "26": 47,
    "27": 48,
    "28": 49,
    "29": 50,
    "3": 51,
    "30": 52,
    "31": 53,
    "32": 54,
    "33": 55,
    "34": 56,
    "35": 57,
    "36": 58,
    "37": 59,
    "38": 60,
    "39": 61,
    "4": 62,
    "40": 63,
    "41": 64,
    "42": 65,
    "43": 66,
    "44": 67,
    "45": 68,
    "46": 69,
    "47": 70,
    "48": 71,
    "49": 72,
    "5": 73,
    "50": 74,
    "51": 75,
    "52": 76,
    "53": 77,
    "54": 78,
    "55": 79,
    "56": 80,
    "57": 81,
    "58": 82,
    "59": 83,
    "6": 84,
    "60": 85,
    "61": 86,
    "62": 87,
    "63": 88,
    "64": 89,
    "65": 90,
    "66": 91,
    "67": 92,
    "68": 93,
    "69": 94,
    "7": 95,
    "70": 96,
    "71": 97,
    "72": 98,
    "73": 99,
    "74": 100,
    "75": 101,
    "76": 102,
    "77": 103,
    "78": 104,
    "79": 105,
    "8": 106,
    "80": 107,
    "81": 108,
    "82": 109,
    "83": 110,
    "84": 111,
    "85": 112,
    "86": 113,
    "87": 114,
    "88": 115,
    "89": 116,
    "9": 117,
    "90": 118,
    "91": 119,
    "92": 120,
    "93": 121,
    "94": 122,
    "95": 123,
    "96": 124,
    "97": 125,
    "98": 126,
    "99": 127
  } ,initializer_range=0.02,max_length=192,max_position_embeddings=512,num_attention_heads=12))
        # BertModel 을 통해 embedding 을 획득하고 classifier 를 활용하여 획득
        self.text_model.num_labels = n_classes_1
        self.text_model.classifier.out_features = n_classes_1

    def forward(self, input_ids , attention_mask):
        """__call__ model special method
        :param input_ids: model input_ids
        :param attention_mask:  model attention_mask
        :return: outputs
        """
        outputs = self.text_model(input_ids=input_ids,
                        attention_mask=attention_mask)

        return outputs

In [170]:
n_classes_1=  all_df['cat1'].unique()

In [174]:
import re
all_df['overview'] =  all_df['overview'].map(lambda x: ' ' .join(re.compile('[ㄱ-힣.]+').findall(x)))
#train_df['overview_re'] = train_df['overview'].map(lambda x : ' '.join([t.strip() if len(t) < 51 else t[:51].strip() for t in x.split('.')])[:512])

In [189]:
def cutting_text(text):
    if len(text) > 512:
        return ' '.join([t.strip() if len(t) < 51 else t[:51].strip() for t in text.split('.')])[:512]
    else:
        return  text

In [212]:
all_df['overview'] = all_df['overview'].map(cutting_text)

In [213]:
overviews = all_df['overview'].values

In [214]:
# class TextSampler(Sampler):

In [482]:
train_dataloader = DataLoader(train_dataset , batch_size=1 , shuffle=False)
valid_dataloader = DataLoader(valid_dataset, batch_size=1, shuffle=False)

In [216]:
EPOCHS = 5
MAX_LEN = 512

In [217]:
from tokenizers import BertWordPieceTokenizer

In [219]:
tokenizer = BertWordPieceTokenizer(
    clean_text=False,
    handle_chinese_chars=False,
    strip_accents=False,
    lowercase=True,
)

In [220]:
#naver_df = pd.read_table('ratings.txt')
#naver_df = naver_df.dropna(how='any')
all_df['overview'].dropna(how='any')

0        소안항은 조용한 섬으로 인근해안이 청정해역으로 일찍이 김 양식을 해서 높은 소득을 ...
1        경기도 이천시 모가면에 있는 골프장으로 대중제 홀이다. 회원제로 개장을 했다가 년 ...
2        금오산성숯불갈비는 한우고기만을 전문적으로 취급하고 사용하는 부식 자재 또한 유기농법...
3        철판 위에서 요리하는 안동찜닭을 맛볼 수 있는 곳이다. 경상북도 안동시에 있는 한식...
4            영업시간 대에 걸쳐 아귀만을 전문으로 취급하는 전통과 역사를 자랑하는 음식점이다.
                               ...                        
16981            해발 에 자리한 식담겸 카페점문점이다. 곤드레밥과 감자전을 판매하고 있다.
16982    설악힐호텔은 동해고속도로 속초톨게이트에서 멀지 않은 관광로 변에 있다. 속초의 대표...
16983    충남 서산시 중심가에 위치한 줌모텔은 프라이버스가 보장되는 조용한 공간으로 가치가 ...
16984    토토큰바위캠핑장은 경기도 가평지역 내에서도 청정지역으로 손꼽히는 지역으로 주변에 화...
16985    포천의 진산으로 불리우는 왕방산 王訪山 에는 천년의 역사를 간직하고 있는 왕산사 王...
Name: overview, Length: 16986, dtype: object

In [541]:
with open('sightseeing_overview.txt', 'w', encoding='utf8') as f:
    f.write('\n\n'.join(all_df['overview']))

In [542]:
data_file = 'sightseeing_overview.txt'
vocab_size = 32000
# limit_alphabet = 1
#limit_alphabet : 병합 전의 초기 토큰의 허용 개수.
limit_alphabet = 6000
min_frequency = 5

tokenizer.train(files=data_file,
                vocab_size=vocab_size,
                limit_alphabet=limit_alphabet,
                min_frequency=min_frequency)

<bound method BaseTokenizer.get_vocab_size of Tokenizer(vocabulary_size=32000, model=BertWordPiece, unk_token=[UNK], sep_token=[SEP], cls_token=[CLS], pad_token=[PAD], mask_token=[MASK], clean_text=False, handle_chinese_chars=False, strip_accents=False, lowercase=True, wordpieces_prefix=##)>

In [223]:
cat1 = all_df['cat1'].values

In [472]:
from sklearn.model_selection import train_test_split
train,valid = train_test_split(all_df)

In [495]:
train_overviews = train['overview']
valid_overviews = valid['overview']
train_cat1 =train['cat1'].values
valid_cat1 = valid['cat1'].values

In [496]:
train_overviews.reset_index(drop=True,inplace=True)

In [497]:
valid_overviews.reset_index(drop=True, inplace=True)

In [500]:
# reset_index가 안되서 keyerror , sampler도 동일한 이유일 수 있다
#train_overviews[12386]
train_dataset = CateDataset(train_overviews, train_cat1,tokenizer)

Text must be str


In [501]:
valid_dataset = CateDataset(valid_overviews , valid_cat1, tokenizer)

Text must be str


In [254]:
from torch.utils.data import Sampler

In [255]:
from sklearn.model_selection import StratifiedKFold

In [235]:
# sampler image id를 가지고 가져온다 dataloader 에 넣으면
class TextSampler(Sampler):
    def __init__(self,
                 # sample_idx,
                 label_encoder,
                 data_source='../sightseeing_ai_hub/input/train.csv'):
        super().__init__(data_source)
        # self.sample_idx = sample_idx
        self.df = pd.read_csv(data_source)
        self.df['cat3_enc'] = label_encoder.fit_transform(self.df['cat3'])
        self.skf = StratifiedKFold(n_splits=4, shuffle=False)
    def __iter__(self):
         # overviews = self.df_images['id'].loc[self.sample_idx]
         for train_idx, test_idx in self.skf.split(self.df['overview'], self.df['cat3_enc']):
            yield train_idx,test_idx
        # return self.sample_idx
        # for idx in self.sample_idx:
            # yield idx
        # return iter(overviews)

    def __len__(self):
        return len(self.df)

In [502]:
#train_dataloader=  DataLoader(train_dataset , batch_size=16 , shuffle=False, sampler=TextSampler)

In [503]:
train_dataloader = DataLoader(train_dataset , batch_size= 1 , shuffle=False)

In [478]:
valid_dataset

In [504]:
valid_dataloader = DataLoader(valid_dataset , batch_size= 1, shuffle=False)


In [294]:
tokenizer.add_special_tokens

<bound method BaseTokenizer.add_special_tokens of Tokenizer(vocabulary_size=42000, model=BertWordPiece, unk_token=[UNK], sep_token=[SEP], cls_token=[CLS], pad_token=[PAD], mask_token=[MASK], clean_text=False, handle_chinese_chars=False, strip_accents=False, lowercase=True, wordpieces_prefix=##)>

In [295]:
tokenizer.id_to_token(0)

'[PAD]'

In [259]:
tokenizer.id_to_token(1)

'[UNK]'

In [361]:
label.long()

tensor([5, 0, 3, 3, 3, 0, 0, 5])

In [ ]:
# BertforSequenceClassification은 너무 오래걸리는듯하다 아니면 영어만되나

In [375]:
import torch_optimizer as optim

In [373]:
from transformers.optimization import get_cosine_with_hard_restarts_schedule_with_warmup

In [480]:
model = CateClassifier(n_classes_1=len(n_classes_1))
optimizer = optim.Lookahead(optim.RAdam(filter(lambda p: p.requires_grad,model.parameters()), lr=5e-5), alpha=0.5, k=5)
scheduler = get_cosine_with_hard_restarts_schedule_with_warmup(optimizer, num_warmup_steps=0 ,num_training_steps=len(train_dataloader))

In [411]:
torch.LongTensor([cat1[0]])
torch.LongTensor(cat1[0])

tensor([0, 0, 0, 0, 0])

[tensor([[25944,  9051,  8277,  ...,     0,     0,     0],
         [ 6659, 13514, 34980,  ...,     0,     0,     0],
         [17015,  3780, 17225,  ...,     0,     0,     0],
         ...,
         [17041, 16583,  6816,  ...,     0,     0,     0],
         [ 3103,  3779,  8930,  ...,     0,     0,     0],
         [39586, 16398, 15604,  ...,     0,     0,     0]]),
 tensor([[1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         ...,
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0]]),
 tensor([[5],
         [0],
         [3],
         [3],
         [3],
         [0],
         [0],
         [5]])]

In [437]:
def calc_accuracy(output, label):
    # pred = torch.max(output,dim=1)
    max_vals, max_indices = torch.max(output,1)
    train_acc = (max_indices == label ).sum().data.cpu().numpy() / max_indices.size()[0]
    return train_acc

In [506]:
# padding 해야 list of batch must be equal size error 만나지 않는다
# 너무 심각하게 오래걸린다..
from tqdm import tqdm,tqdm_notebook

for e in range(EPOCHS):
    test_acc =0.0
    train_acc =0.0
    model.train()
    for step , (input_ids, attention_mask, label) in tqdm(enumerate(train_dataloader)):
        optimizer.zero_grad()

        model(input_ids,attention_mask)
        loss_fn = nn.CrossEntropyLoss()
        output = model(input_ids,attention_mask)
        loss = loss_fn(output.logits,label[0])
        loss.backward()
        optimizer.step()
        scheduler.step()
    print("epoch {} train acc {}".format(e+1,train_acc/(step+1)))

0it [00:02, ?it/s]


KeyboardInterrupt: 

In [ ]:
for batch_id, (token_ids, attention_mask, label) in enumerate(tqdm_notebook(valid_dataloader)):
    token_ids = token_ids
    output = model(input_ids,attention_mask)
    test_acc += calc_accuracy(output.logits , label)
    if batch_id ==50:
        break
print("epoch {} test acc {}".format(e+1, test_acc / (step+1)))


KeyboardInterrupt



In [512]:
from transformers import RobertaForSequenceClassification

In [570]:
model = RobertaForSequenceClassification.from_pretrained('klue/roberta-large', num_labels =6)

Some weights of the model checkpoint at klue/roberta-large were not used when initializing RobertaForSequenceClassification: ['lm_head.layer_norm.bias', 'lm_head.dense.weight', 'lm_head.layer_norm.weight', 'lm_head.decoder.bias', 'lm_head.decoder.weight', 'lm_head.bias', 'lm_head.dense.bias']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at klue/roberta-large and are newly initialized: ['classifier.dense.weight', 'classifier.out_proj.bias', 'class

In [ ]:
def bert_tokenizer(sent, MAX_LEN, tokenizer):

    encoded_dict=tokenizer.encode_plus(
    text = sent,
    add_special_tokens=True,
    max_length=MAX_LEN,
    pad_to_max_length=True,
    return_attention_mask=True,
    truncation = True)

    input_id=encoded_dict['input_ids']
    attention_mask=encoded_dict['attention_mask']
    #token_type_id = encoded_dict['token_type_ids']
    token_type_id = 0

    return input_id, attention_mask, token_type_id


In [528]:
from transformers import PreTrainedTokenizer


In [535]:

VOCAB_FILES_NAMES = {
    "vocab_file": {
        "monologg/kobert": "https://s3.amazonaws.com/models.huggingface.co/bert/monologg/kobert/tokenizer_78b3253a26.model",
        "monologg/kobert-lm": "https://s3.amazonaws.com/models.huggingface.co/bert/monologg/kobert-lm/tokenizer_78b3253a26.model",
        "monologg/distilkobert": "https://s3.amazonaws.com/models.huggingface.co/bert/monologg/distilkobert/tokenizer_78b3253a26.model"
    },
    "vocab_txt": {
        "monologg/kobert": "https://s3.amazonaws.com/models.huggingface.co/bert/monologg/kobert/vocab.txt",
        "monologg/kobert-lm": "https://s3.amazonaws.com/models.huggingface.co/bert/monologg/kobert-lm/vocab.txt",
        "monologg/distilkobert": "https://s3.amazonaws.com/models.huggingface.co/bert/monologg/distilkobert/vocab.txt"
    }
}


PRETRAINED_VOCAB_FILES_MAP = {
    "vocab_file": {
        "monologg/kobert": "https://s3.amazonaws.com/models.huggingface.co/bert/monologg/kobert/tokenizer_78b3253a26.model",
        "monologg/kobert-lm": "https://s3.amazonaws.com/models.huggingface.co/bert/monologg/kobert-lm/tokenizer_78b3253a26.model",
        "monologg/distilkobert": "https://s3.amazonaws.com/models.huggingface.co/bert/monologg/distilkobert/tokenizer_78b3253a26.model"
    },
    "vocab_txt": {
        "monologg/kobert": "https://s3.amazonaws.com/models.huggingface.co/bert/monologg/kobert/vocab.txt",
        "monologg/kobert-lm": "https://s3.amazonaws.com/models.huggingface.co/bert/monologg/kobert-lm/vocab.txt",
        "monologg/distilkobert": "https://s3.amazonaws.com/models.huggingface.co/bert/monologg/distilkobert/vocab.txt"
    }
}
PRETRAINED_POSITIONAL_EMBEDDINGS_SIZES = {
    "monologg/kobert": 512,
    "monologg/kobert-lm": 512,
    "monologg/distilkobert": 512
}

PRETRAINED_INIT_CONFIGURATION = {
    "monologg/kobert": {"do_lower_case": False},
    "monologg/kobert-lm": {"do_lower_case": False},
    "monologg/distilkobert": {"do_lower_case": False}
}

SPIECE_UNDERLINE = u'▁'

In [536]:

class KoBertTokenizer(PreTrainedTokenizer):
    """
        SentencePiece based tokenizer. Peculiarities:
            - requires `SentencePiece <https://github.com/google/sentencepiece>`_
    """
    vocab_files_names = PRETRAINED_VOCAB_FILES_MAP
    pretrained_vocab_files_map = PRETRAINED_VOCAB_FILES_MAP
    pretrained_init_configuration = PRETRAINED_INIT_CONFIGURATION
    max_model_input_sizes = PRETRAINED_POSITIONAL_EMBEDDINGS_SIZES

    def __init__(
            self,
            vocab_file,
            vocab_txt,
            do_lower_case=False,
            remove_space=True,
            keep_accents=False,
            unk_token="[UNK]",
            sep_token="[SEP]",
            pad_token="[PAD]",
            cls_token="[CLS]",
            mask_token="[MASK]",
            **kwargs):
        super().__init__(
            unk_token=unk_token,
            sep_token=sep_token,
            pad_token=pad_token,
            cls_token=cls_token,
            mask_token=mask_token,
            **kwargs
        )

        # Build vocab
        self.token2idx = dict()
        self.idx2token = []
        with open(vocab_txt, 'r', encoding='utf-8') as f:
            for idx, token in enumerate(f):
                token = token.strip()
                self.token2idx[token] = idx
                self.idx2token.append(token)

        #self.max_len_single_sentence = self.max_len - 2  # take into account special tokens
        #self.max_len_sentences_pair = self.max_len - 3  # take into account special tokens

        try:
            import sentencepiece as spm
        except ImportError:
            logger.warning("You need to install SentencePiece to use KoBertTokenizer: https://github.com/google/sentencepiece"
                           "pip install sentencepiece")

        self.do_lower_case = do_lower_case
        self.remove_space = remove_space
        self.keep_accents = keep_accents
        self.vocab_file = vocab_file
        self.vocab_txt = vocab_txt
        # 미리 학습한 sentencepiece model vocab file 사용 (위에서 정의)
        self.sp_model = spm.SentencePieceProcessor()
        self.sp_model.Load(vocab_file)
    # getter setter 되도록 읽기 전용 필드
    @property
    def vocab_size(self):
        return len(self.idx2token)
    #  setstate 로 들어간 것은 getstate 로 얻을 수 있다
    def __getstate__(self):
        state = self.__dict__.copy()
        state["sp_model"] = None
        return state

    def __setstate__(self, d):
        self.__dict__ = d
        try:
            import sentencepiece as spm
        except ImportError:
            logger.warning("You need to install SentencePiece to use KoBertTokenizer: https://github.com/google/sentencepiece"
                           "pip install sentencepiece")
        self.sp_model = spm.SentencePieceProcessor()
        self.sp_model.Load(self.vocab_file)

    def preprocess_text(self, inputs):
        if self.remove_space:
            outputs = " ".join(inputs.strip().split())
        else:
            outputs = inputs
        outputs = outputs.replace("``", '"').replace("''", '"')

        if not self.keep_accents:
            outputs = unicodedata.normalize('NFKD', outputs)
            outputs = "".join([c for c in outputs if not unicodedata.combining(c)])
        if self.do_lower_case:
            outputs = outputs.lower()

        return outputs

    def _tokenize(self, text, return_unicode=True, sample=False):
        """ Tokenize a string. """
        text = self.preprocess_text(text)

        if not sample:
            pieces = self.sp_model.EncodeAsPieces(text)
        else:
            pieces = self.sp_model.SampleEncodeAsPieces(text, 64, 0.1)
        new_pieces = []
        for piece in pieces:
            if len(piece) > 1 and piece[-1] == str(",") and piece[-2].isdigit():
                cur_pieces = self.sp_model.EncodeAsPieces(piece[:-1].replace(SPIECE_UNDERLINE, ""))
                if piece[0] != SPIECE_UNDERLINE and cur_pieces[0][0] == SPIECE_UNDERLINE:
                    if len(cur_pieces[0]) == 1:
                        cur_pieces = cur_pieces[1:]
                    else:
                        cur_pieces[0] = cur_pieces[0][1:]
                cur_pieces.append(piece[-1])
                new_pieces.extend(cur_pieces)
            else:
                new_pieces.append(piece)

        return new_pieces

    def _convert_token_to_id(self, token):
        """ Converts a token (str/unicode) in an id using the vocab. """
        return self.token2idx.get(token, self.token2idx[self.unk_token])

    def _convert_id_to_token(self, index, return_unicode=True):
        """Converts an index (integer) in a token (string/unicode) using the vocab."""
        return self.idx2token[index]

    def convert_tokens_to_string(self, tokens):
        """Converts a sequence of tokens (strings for sub-words) in a single string."""
        out_string = "".join(tokens).replace(SPIECE_UNDERLINE, " ").strip()
        return out_string

    def build_inputs_with_special_tokens(self, token_ids_0, token_ids_1=None):
        """
        Build model inputs from a sequence or a pair of sequence for sequence classification tasks
        by concatenating and adding special tokens.
        A RoBERTa sequence has the following format:
            single sequence: [CLS] X [SEP]
            pair of sequences: [CLS] A [SEP] B [SEP]
        """
        if token_ids_1 is None:
            return [self.cls_token_id] + token_ids_0 + [self.sep_token_id]
        cls = [self.cls_token_id]
        sep = [self.sep_token_id]
        return cls + token_ids_0 + sep + token_ids_1 + sep

    def get_special_tokens_mask(self, token_ids_0, token_ids_1=None, already_has_special_tokens=False):
        """
        Retrieves sequence ids from a token list that has no special tokens added. This method is called when adding
        special tokens using the tokenizer ``prepare_for_model`` or ``encode_plus`` methods.
        Args:
            token_ids_0: list of ids (must not contain special tokens)
            token_ids_1: Optional list of ids (must not contain special tokens), necessary when fetching sequence ids
                for sequence pairs
            already_has_special_tokens: (default False) Set to True if the token list is already formated with
                special tokens for the model
        Returns:
            A list of integers in the range [0, 1]: 0 for a special token, 1 for a sequence token.
        """

        if already_has_special_tokens:
            if token_ids_1 is not None:
                raise ValueError(
                    "You should not supply a second sequence if the provided sequence of "
                    "ids is already formated with special tokens for the model."
                )
            return list(map(lambda x: 1 if x in [self.sep_token_id, self.cls_token_id] else 0, token_ids_0))

        if token_ids_1 is not None:
            return [1] + ([0] * len(token_ids_0)) + [1] + ([0] * len(token_ids_1)) + [1]
        return [1] + ([0] * len(token_ids_0)) + [1]

    def create_token_type_ids_from_sequences(self, token_ids_0, token_ids_1=None):
        """
        Creates a mask from the two sequences passed to be used in a sequence-pair classification task.
        A BERT sequence pair mask has the following format:
        0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1
        | first sequence    | second sequence
        if token_ids_1 is None, only returns the first portion of the mask (0's).
        """
        sep = [self.sep_token_id]
        cls = [self.cls_token_id]
        if token_ids_1 is None:
            return len(cls + token_ids_0 + sep) * [0]
        return len(cls + token_ids_0 + sep) * [0] + len(token_ids_1 + sep) * [1]

    def save_vocabulary(self, save_directory):
        """ Save the sentencepiece vocabulary (copy original file) and special tokens file
            to a directory.
        """
        if not os.path.isdir(save_directory):
            logger.error("Vocabulary path ({}) should be a directory".format(save_directory))
            return

        # 1. Save sentencepiece model
        out_vocab_model = os.path.join(save_directory, VOCAB_FILES_NAMES["vocab_file"])

        if os.path.abspath(self.vocab_file) != os.path.abspath(out_vocab_model):
            copyfile(self.vocab_file, out_vocab_model)

        # 2. Save vocab.txt
        index = 0
        out_vocab_txt = os.path.join(save_directory, VOCAB_FILES_NAMES["vocab_txt"])
        with open(out_vocab_txt, "w", encoding="utf-8") as writer:
            for token, token_index in sorted(self.token2idx.items(), key=lambda kv: kv[1]):
                if index != token_index:
                    logger.warning(
                        "Saving vocabulary to {}: vocabulary indices are not consecutive."
                        " Please check that the vocabulary is not corrupted!".format(out_vocab_txt)
                    )
                    index = token_index
                writer.write(token + "\n")
                index += 1

        return out_vocab_model, out_vocab_txt

In [ ]:
import sentencepiece as spm



In [538]:
# 카카오 sentencepiece 카테고리분류기에서 활용 필요
# tokenizer = KoBertTokenizer.from_pretrained('klue/roberta-large',  cache_dir='bert_ckpt', do_lower_case=False)
# print('load kobert')

In [ ]:
# input_id, attention_mask,_ =  bert_tokenizer(train_sent, MAX_LEN=MAX_LEN, tokenizer=tokenizer)

In [549]:
tokenizer = RobertaTo

'소안항은 조용한 섬으로 인근해안이 청정해역으로 일찍이 김 양식을 해서 높은 소득을 올리고 있으며 바다낚시터로도 유명하다. 항 주변에 설치된 양식장들은 섬사람들의 부지런한 생활상을 고스 란히 담고 있으며 일몰 때 섬의 정경은 바다의 아름다움을 그대로 품고 있는 듯하다. 또한 섬에는 각시여 전설 도둑바위 등의 설화가 전해 내려오고 있으며 매년 정월 풍어제 풍속이 이어지고 있다.'

In [551]:
enc = tokenizer.encode(all_df['overview'].values[0])

In [572]:
enc_ids = torch.tensor(enc.ids)
attention_mask = torch.tensor(enc.attention_mask)

In [574]:
model( enc_ids, attention_mask )

ValueError: not enough values to unpack (expected 2, got 1)

In [370]:
x = torch.Tensor([[0.8982,0.805,0.6393]])
y = torch.LongTensor([3])

tensor(4.9173, grad_fn=<NllLossBackward0>)

{'input_ids': [[tensor([25944]),
   tensor([9051]),
   tensor([8277]),
   tensor([10773]),
   tensor([6579]),
   tensor([8992]),
   tensor([3557]),
   tensor([25529]),
   tensor([15581]),
   tensor([2050]),
   tensor([11971]),
   tensor([8348]),
   tensor([6937]),
   tensor([34801]),
   tensor([12465]),
   tensor([3020]),
   tensor([3459]),
   tensor([6926]),
   tensor([9057]),
   tensor([29689]),
   tensor([6828]),
   tensor([2736]),
   tensor([21214]),
   tensor([37501]),
   tensor([3601]),
   tensor([16646]),
   tensor([9558]),
   tensor([2386]),
   tensor([3617]),
   tensor([10193]),
   tensor([6500]),
   tensor([8289]),
   tensor([2338]),
   tensor([6532]),
   tensor([19081]),
   tensor([3567]),
   tensor([32454]),
   tensor([3625]),
   tensor([7529]),
   tensor([20661]),
   tensor([6883]),
   tensor([6625]),
   tensor([22136]),
   tensor([7298]),
   tensor([20384]),
   tensor([6500]),
   tensor([7022]),
   tensor([14805]),
   tensor([39797]),
   tensor([3682]),
   tensor([26168])

In [264]:
len(data['input_ids'])

512

In [279]:
data['input_ids'][0]

tensor([25944])

In [280]:
len(data['input_ids'][1])

1

TypeError: __init__() missing 3 required positional arguments: 'text', 'cat1', and 'tokenizer'